# Generated by Django 3.2.9 on 2021-12-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogImgs', to='blog.blog'),
        ),
    ]
